### ISSUE TITLE
I used lazy.nvim to install the plugin, but there is no CopilotChat command on the command line.

### ISSUE THREAD

**Issue by whxcode** [gptlang/CopilotChat.nvim#1]
I have correctly executed $ pip install -r requirements.txt in the .local/share/nvim/lazy/CopilotChat.nvim directory.

![image](https://github.com/gptlang/CopilotChat.nvim/assets/44012914/84174c73-63ec-4088-8e1a-01de0ad8c663)

**Comment by gptlang** [comment]
The installation instructions are in the `readme.md`. I have yet to add compatibility with Lazy but that is on the roadmap.

**Comment by jellydn** [comment]
Here is my workaround for using with LazyVim.

```lua
--- Send reminder to quickfix list for manual steps
---@param line string
local function send_to_quickfix(line)
  vim.fn.setqflist({ { filename = "CopilotChat.nvim", lnum = 0, text = line } }, "a")
end

return {
  -- Import the copilot plugin
  { import = "lazyvim.plugins.extras.coding.copilot" },
  {
    "gptlang/CopilotChat.nvim",
    build = function()
      local copilot_chat_dir = vim.fn.stdpath("data") .. "/lazy/CopilotChat.nvim"
      -- Copy remote plugin to config folder
      vim.fn.system({ "cp", "-r", copilot_chat_dir .. "/rplugin", vim.fn.stdpath("config") })

      -- Notify the user about manual steps
      send_to_quickfix("Please run 'pip install -r " .. copilot_chat_dir .. "/requirements.txt'.")
      send_to_quickfix("Afterwards, open Neovim and run ':UpdateRemotePlugins', then restart Neovim.")

      -- NOTE: add below to plugin.py if you want to change wrap and filetype
      -- self.nvim.command("setlocal filetype=markdown")
      -- self.nvim.command("setlocal wrap")
    end,
  },
}
```

**Comment by gptlang** [comment]
Sorry, I'm not quite experienced with lua/neovim. Where should I be putting this? Thank you

**Comment by jellydn** [comment]
The `init` should have `setup` like this @gptlang https://github.com/jellydn/my-note.nvim/blob/main/lua/my-note/init.lua#L116

The workaround is for someone is using `lazy.nvim` as the package manager. So it would be different way.

>Where should I be putting this? 

You could add this as example usage. Here is my setup https://github.com/jellydn/lazy-nvim-ide/commit/5128bc3260f463ff32e060127da6be1be40fe345
