### ISSUE TITLE
Yank to unnamed register?

### ISSUE THREAD

**Issue by cjoke** [gptlang/CopilotChat.nvim#10]
First I want to thank you for this awesome plugin!
In combination with copilot.vim this is the holy grail! :) 

I never understood yank into the unnamed register, so I asked copilotchat if I could paste code into the unnamed register where I have the dialog with copilotchat. and it said yes. It also said earlier when I asked it to read the code from the other buffer, and it told me that , thats impossible. but I could paste into the buffer where we had the dialog. so it was. I thought this was awesome, and started thinking about making some ways to make it easier a keymap or something so I started looking and do the philosphi x) well, never got so far. But!

Today I did write code with my co-"worker" and thought with my newb-brain what if there's a :paste  command where I can after asking just put a :paste behind. so I did, without looking.  I did this following ``` :CopilotChat make comments to this code :paste ``` and copilotchat answere : sure no problem and did all the lines I had yanked into memory. commented and all things looked good. 

After a coffeebreake I went back to computer and thought, well, I should check out this :paste command in neovim. and got the answere from neovim. error :paste is not a command. so my question is . copilot says that It cant read buffers, thats probably right. but I dont get it. Ill try to answere my self. if I want copilotchat to read the yank, I have to tell it to ? sure it understood that :paste should make him read the yank memory.  well! Onely thing I could complain over is that explanation about yank into unnamed buffer, maby a little more teaspoon for mortal newbs like me =)

Anyways, this is awesome! completely love it!
copilot and code in 1 buffer and a vsplit with copilotchat is a very , very nice feeling! 
so thank you! very very much =)

**Comment by Sophistiqq** [comment]
I have successfully installed the plugin but still the :CopilotChat command still not available to me, how did you do it?

**Comment by gptlang** [comment]
> I have successfully installed the plugin but still the :CopilotChat command still not available to me, how did you do it?

How did you install it? Make sure to run `:UpdateRemotePlugins` and `:q`. Then open neovim again and it should work

**Comment by gptlang** [comment]
@cjoke 

The unnamed register is the default register code is yanked to.

So for example, if you highlight a piece of text in visual mode and press `y`, it yanks it to the unnamed register.

**Comment by gptlang** [comment]
CopilotChat is hard coded to be fed the contents of your unnamed register (whatever you most recently yanked). You don't need to tell it to do anything

**Comment by cjoke** [comment]
That is awesome, soz for newb questions. Thanks for response! Nicest part is that the plugin is written in python. neovim needs more python! ;) Ive been struggling with lua and config last months! =) thanks again!
