### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cjoke** [gptlang/CopilotChat.nvim#13]
I got this since yesterday. 
I have  deleted ~/.local/share/nvim/lazy/Copilot* and ~/config/github-config/ .
and reinstalled plugins : copilot and copilogchat
copilot still works as normal.

```error caught in async handler '/home/username/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/plugin.py:command:CopilotChat [['hi']]'
Traceback (most recent call last):
  File "/home/username/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/plugin.py", line 71, in copilotChat
    for token in self.copilot.ask(prompt, code, language=file_type):
  File "/home/username/.local/share/nvim/lazy/CopilotChat.nvim/rplugin/python3/copilot.py", line 119, in ask
    content = line["choices"][0]["delta"]["content"]
              ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by gptlang** [comment]
Open up Lazy (`:lazy`) and update the extension

**Comment by cjoke** [comment]
> Open up Lazy (`:lazy`) and update the extension

Awesome work! Thank you. :)

**Comment by cjoke** [comment]
I close this now, soz for extra comment! =)

**Comment by ecosse3** [comment]
@gptlang Should it be reopened? I have this issue after fresh installation:

```
error caught in async handler '/Users/name/.config/nvim/rplugin/python3/plugin.py:command:CopilotChat [['explain code']]'
Traceback (most recent call last):
  File "/Users/name/.config/nvim/rplugin/python3/plugin.py", line 71, in copilotChat
    for token in self.copilot.ask(prompt, code, language=file_type):
  File "/Users/name/.config/nvim/rplugin/python3/copilot.py", line 119, in ask
    content = line["choices"][0]["delta"]["content"]
              ~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

NVIM v0.10.0-dev-1988+g1ef60ea65
Build type: RelWithDebInfo
LuaJIT 2.1.1703358377
Python 3.11.7
pip 23.3.2 from /opt/homebrew/lib/python3.11/site-packages/pip (python 3.11)

**Comment by cjoke** [comment]
I synced my fork today(few hours ago), and did a Lazy update, no problem here. I also have that 
``` content = line["choices"][0]["delta"]["content"] ``` on line 121 in copilot.py (not line 119). maby your missing out something ? 

I did fallback on nvim v0.9.5 latest stable a week ago. I also use python 3.11.7

**Comment by gptlang** [comment]
After updating, try doing `:UpdateRemotePlugins`. 

> on line 121 in copilot.py

That line is on 124 on the latest version

**Comment by ecosse3** [comment]
@gptlang Works now. Had to copy again the `rplugin` since lua cp command from another PR didn't work on build. After `:UpdateRemotePlugins` it works now! Thank you

**Comment by gptlang** [comment]
> Had to copy again the rplugin since lua cp command from another PR didn't work on build

Could you expand on that? Not sure how to fix it
