### ISSUE TITLE
Multibyte characters in chat messages are broken @ db879715076ed227a3be330d0bad857ce5cccb55

### ISSUE THREAD

**Issue by yfujita-skgcat** [gptlang/CopilotChat.nvim#14]
- How to reproduce

1. select and yank codes
2. :OpenCopilotChat explain in Japanese

Answer messages are broken because the messages include the multi-byte characters.

- How to resolve

modify plugin.py as follows:

`

        self.nvim.api.buf_set_option(buf, "fileencoding", "utf-8")

        for token in self.copilot.ask(prompt, code, language=file_type):
            buffer_lines = self.nvim.api.buf_get_lines(buf, 0, -1, 0)
            last_line_row = len(buffer_lines) - 1
            # last_line_col = len(buffer_lines[-1]) # commented out

            # add following codes
            # Get current buffer encoding
            # encoding = self.nvim.api.buf_get_option(buf, "fileencoding")
            last_line = buffer_lines[-1]
            # UTF-8 encode and get byte index
            last_line_col = len(last_line.encode('utf-8'))

            self.nvim.api.buf_set_text(
                buf,
                last_line_row,
                last_line_col,
                last_line_row,
                last_line_col,
                token.split("\n"),
            )

`

**Comment by gptlang** [comment]
Thank you!
